version: '1.0.0'

services:
  hunter-judge:
    image: hunter-judge
    container_name: hunter-judge
    profiles:
      - services
    build: 
      context: judge
      dockerfile: Dockerfile
    tty : true
    
  hunter-backend:
    image: hunter-backend
    container_name: hunter-backend
    profiles:
      - services
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - hunter-judge
    command: "npm run start-${ENV}"
    volumes:
      - ./backend:/home/app
    ports:
      - "8080:8080"
  
    
