version: '1.0.0'

services:  
  hunter-database:
    container_name: hunter-database
    image: mysql
    profiles:
      - services
    ports:
      - "${DB_PORT}:${DB_PORT}"
  hunter-backend:
    image: hunter-backend
    container_name: hunter-backend
    profiles:
      - services
    build:
      context: backend
      dockerfile: Dockerfile
    command: "npm run start-${ENV}"
    depends_on:
      - hunter-database
    ports:
      - "8080:8080"
  
    
