version: "1.0.0"

services:
    hunter-backend:
        image: msc24x/hunter-backend:latest
        container_name: hunter-backend
        ports:
            - 8080:8080
        restart: always

        build:
            context: backend
            args:
                ENV: prod
            dockerfile: Dockerfile
