version: '1.0.0'

services:    
  hunter-backend:
    image: hunter-backend
    container_name: hunter-backend
    profiles:
      - services
    build:
      context: backend
      dockerfile: Dockerfile
    command: "npm run start-${ENV}"
    restart: always
    volumes:
      - ./backend:/home/app
    ports:
      - "8080:8080"
  
    
