-- AlterTable
ALTER TABLE `community` MODIFY `status` ENUM('PENDING_APPROVAL', 'APPROVED', 'NOT_APPROVED', 'DISABLED') NOT NULL DEFAULT 'PENDING_APPROVAL';

-- AlterTable
ALTER TABLE `community_member` MODIFY `status` ENUM('PENDING_APPROVAL', 'APPROVED', 'NOT_APPROVED', 'DISABLED') NOT NULL DEFAULT 'PENDING_APPROVAL';
